'use strict';

function tcRangeV2_(value,min,max,name,allowBlank){
  if(value===null||value===undefined||String(value).trim()===''){if(allowBlank)return;throw new Error('FIELD_REQUIRED:'+name);}
  const n=Number(value);if(!Number.isFinite(n)||n<min||n>max)throw new Error('FIELD_RANGE:'+name);return n;
}
function tcValidateRirV2_(value,name){
  if(String(value||'').trim()==='')return;const vals=RFormAnalyzer.parseRir(value);if(!vals.length)throw new Error('FIELD_FORMAT:'+name);const raw=String(value).split(/[\/;,\s]+/).filter(Boolean);if(vals.length!==raw.length)throw new Error('FIELD_RANGE:'+name);
}
function tcValidateCheckInputV2_(p){
  if(!p||typeof p!=='object')throw new Error('PAYLOAD_INVALID');['exercise_name','actual_sets','actual_reps','overall_result'].forEach(function(k){if(String(p[k]||'').trim()==='')throw new Error('FIELD_REQUIRED:'+k);});
  if(String(p.exercise_name||'').trim().length>120||String(p.overall_result||'').trim().length>400||String(p.quality_comment||'').trim().length>400||String(p.additional_event||'').trim().length>300)throw new Error('FIELD_TOO_LONG');
  tcRangeV2_(p.actual_sets,1,30,'actual_sets',false);tcRangeV2_(p.actual_reps,1,100,'actual_reps',false);tcRangeV2_(p.plan_sets,1,30,'plan_sets',true);tcRangeV2_(p.plan_reps,1,100,'plan_reps',true);tcRangeV2_(p.actual_load,0,1000,'actual_load',true);tcRangeV2_(p.plan_load,0,1000,'plan_load',true);tcRangeV2_(p.pain_0_10,0,10,'pain_0_10',true);
  if(String(p.actual_rir||'').trim()===''&&String(p.effort||'').trim()==='')throw new Error('FIELD_REQUIRED:intensity');tcValidateRirV2_(p.actual_rir,'actual_rir');tcValidateRirV2_(p.target_rir,'target_rir');if(JSON.stringify(p).length>RFORM_TCV1.MAX_PAYLOAD_CHARS)throw new Error('PAYLOAD_TOO_LARGE');
}
function tcFallbackAnalysisV2_(fact){return{engine:'RFORM_DETERMINISTIC',version:RFORM_ANALYZER_VERSION,fact:fact||'Тренировка сохранена.',signal:'Анализ временно недоступен.',signal_code:'ANALYSIS_UNAVAILABLE',interpretation:'Факт тренировки сохранён. Вывод можно повторить позже без повторной записи тренировки.',decision_direction:'Пока не менять решение на основании недоступного анализа.',checkpoint:'',comparison_status:'INSUFFICIENT_DATA',comparison_note:'Анализ не завершён.',trend_status:'NONE',confidence:'LOW',insufficient_data:true,safety_flag:false,analysis_unavailable:true};}
function tcSubmitCheckV2_(participant,eventId,payload){
  if(!tcWritesEnabled_())throw new Error('PRODUCTION_WRITES_DISABLED');tcValidateCheckInputV2_(payload);const lock=LockService.getScriptLock();lock.waitLock(15000);
  try{
    const dup=tcIngestFind_(eventId);if(dup&&dup.obj.processing_status==='APPLIED'){const hit=tcHistory_(participant.participant_id,10).filter(function(x){return x.check_id===dup.obj.check_id;})[0];if(hit)return hit;}
    const previous=tcHistory_(participant.participant_id,3);payload.goal=participant.goal||payload.goal||'';const ss=tcSs_(),s=tcRequireSheet_(ss,RFORM_TCV1.SHEETS.CHECKS),h=tcHeaderMap_(s),row=Math.max(2,s.getLastRow()+1),checkId='RTC-TG-'+Utilities.formatDate(new Date(),'Etc/UTC','yyyyMMdd')+'-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toUpperCase(),plan=tcBuildPlanText_(payload),fact=tcBuildFactText_(payload),intensity=[payload.actual_rir?('RIR '+payload.actual_rir):'',payload.effort||''].filter(Boolean).join(' · ');
    tcSetRowValues_(s,h,row,{check_id:checkId,participant_id:participant.participant_id,test_status:'COMPLETED',test_date:String(payload.session_date||'').slice(0,10),session_date:String(payload.session_date||'').slice(0,10),training_context:'TELEGRAM_V1',plan:plan,fact:fact,rir_summary:intensity,quality_comment:String(payload.quality_comment||payload.quality_rating||''),participant_decision:'',data_quality:'COMPLETE',analyst:'RFORM_DETERMINISTIC',recommendation_status:'ANALYSIS_PENDING',input_json:JSON.stringify(payload),portable_prompt_version:RFORM_TCV1.PORTABLE_PROMPT_VERSION});
    const ingest=tcIngestAppend_(eventId,checkId,participant.participant_id,'MINI_APP','PROCESSING','Training fact stored; analysis pending',{action:'check_submit'}),ps=tcRequireSheet_(ss,RFORM_TCV1.SHEETS.PARTICIPANTS),ph=tcHeaderMap_(ps),prow=tcFindRow_(ps,ph.participant_id,participant.participant_id);if(prow)tcSetRowValues_(ps,ph,prow,{current_check_id:checkId,profile_updated_at:tcNowIso_()});SpreadsheetApp.flush();
    let analysis;
    try{
      analysis=RFormAnalyzer.analyzeTrainingCheck(payload,previous);tcSetRowValues_(s,h,row,{test_status:'REPORTED',analyst_key_deviation:analysis.signal,analyst_interpretation:analysis.interpretation,report_next_step:analysis.checkpoint,data_quality:analysis.insufficient_data?'PARTIAL':'COMPLETE',reported_at:tcNowIso_(),recommendation_status:'READY',recommendation_summary:analysis.decision_direction,analysis_engine:analysis.engine,analysis_version:analysis.version,signal_code:analysis.signal_code,comparison_status:analysis.comparison_status,comparison_note:analysis.comparison_note,trend_status:analysis.trend_status,confidence:analysis.confidence,insufficient_data:analysis.insufficient_data,safety_flag:analysis.safety_flag,checkpoint_status:'PROPOSED'});tcIngestStatus_(ingest,'APPLIED','','Training Check stored and analyzed');tcEvent_(participant.participant_id,checkId,'analysis_completed','SERVER',participant.is_test_user,{engine:analysis.engine,version:analysis.version});tcEvent_(participant.participant_id,checkId,'checkpoint_proposed','SERVER',participant.is_test_user,{});
    }catch(err){analysis=tcFallbackAnalysisV2_(fact);tcSetRowValues_(s,h,row,{recommendation_status:'ANALYSIS_ERROR',analysis_engine:'RFORM_DETERMINISTIC',analysis_version:RFORM_ANALYZER_VERSION,signal_code:'ANALYSIS_UNAVAILABLE',comparison_status:'INSUFFICIENT_DATA',confidence:'LOW',insufficient_data:true});tcIngestStatus_(ingest,'APPLIED','','Training fact stored; analysis unavailable');}
    tcEvent_(participant.participant_id,checkId,'check_completed','MINI_APP',participant.is_test_user,{signal_code:analysis.signal_code});if(previous.length===1)tcEvent_(participant.participant_id,checkId,'second_check_completed','SERVER',participant.is_test_user,{});else if(previous.length>=2)tcEvent_(participant.participant_id,checkId,'third_check_completed','SERVER',participant.is_test_user,{});SpreadsheetApp.flush();return{check_id:checkId,session_date:String(payload.session_date||'').slice(0,10),input:payload,analysis:analysis,checkpoint_status:analysis.analysis_unavailable?'ANALYSIS_ERROR':'PROPOSED'};
  }finally{lock.releaseLock();}
}
function tcRetryAnalysis_(participant,checkId){
  if(!tcWritesEnabled_())throw new Error('PRODUCTION_WRITES_DISABLED');const lock=LockService.getScriptLock();lock.waitLock(15000);try{const ss=tcSs_(),s=tcRequireSheet_(ss,RFORM_TCV1.SHEETS.CHECKS),h=tcHeaderMap_(s),row=tcFindRow_(s,h.check_id,checkId);if(!row)throw new Error('CHECK_NOT_FOUND');const stored=tcRowObject_(s,h,row);if(stored.participant_id!==participant.participant_id)throw new Error('ACCESS_DENIED');let payload={};try{payload=JSON.parse(stored.input_json||'{}');}catch(_){throw new Error('INPUT_NOT_RECOVERABLE');}const history=tcHistory_(participant.participant_id,10).filter(function(x){return x.check_id!==checkId;}).slice(-3),analysis=RFormAnalyzer.analyzeTrainingCheck(payload,history);tcSetRowValues_(s,h,row,{test_status:'REPORTED',analyst_key_deviation:analysis.signal,analyst_interpretation:analysis.interpretation,report_next_step:analysis.checkpoint,data_quality:analysis.insufficient_data?'PARTIAL':'COMPLETE',reported_at:tcNowIso_(),recommendation_status:'READY',recommendation_summary:analysis.decision_direction,analysis_engine:analysis.engine,analysis_version:analysis.version,signal_code:analysis.signal_code,comparison_status:analysis.comparison_status,comparison_note:analysis.comparison_note,trend_status:analysis.trend_status,confidence:analysis.confidence,insufficient_data:analysis.insufficient_data,safety_flag:analysis.safety_flag,checkpoint_status:'PROPOSED'});tcEvent_(participant.participant_id,checkId,'analysis_completed','SERVER',participant.is_test_user,{retry:true,engine:analysis.engine,version:analysis.version});tcEvent_(participant.participant_id,checkId,'checkpoint_proposed','SERVER',participant.is_test_user,{retry:true});SpreadsheetApp.flush();return{check_id:checkId,session_date:stored.session_date,input:payload,analysis:analysis,checkpoint_status:'PROPOSED'};}finally{lock.releaseLock();}
}
function tcProductEvent_(participant,eventName,metadata){const allowed=['bot_started','onboarding_started','check_started'];if(allowed.indexOf(String(eventName||''))<0)throw new Error('EVENT_NOT_ALLOWED');tcEvent_(participant.participant_id,'',String(eventName),'MINI_APP',participant.is_test_user,metadata||{});return{ok:true};}
