'use strict';
(()=>{
const tg=window.Telegram&&window.Telegram.WebApp;const cfg=window.RFORM_TC_CONFIG||{};const API=String(cfg.apiBase||'').replace(/\/$/,'');const $=id=>document.getElementById(id);let profile=null,history=[],currentCheck=null,pendingResolver=null,requestTimer=null;
const views=['loading','telegramOnly','privacyIntro','onboarding','home','checkView','resultView','historyView','settingsView','privacyView','promptView'];
function show(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:'smooth'});}
function banner(msg){$('banner').textContent=msg;$('banner').classList.remove('hidden');setTimeout(()=>$('banner').classList.add('hidden'),4500);}
function value(id){return String($(id).value||'').trim();}
function n(id){const v=value(id);if(!v)return '';const x=Number(v.replace(',','.'));return Number.isFinite(x)?x:'';}
function today(){const d=new Date(),o=d.getTimezoneOffset()*60000;return new Date(d-o).toISOString().slice(0,10);}
function eventId(){return 'web-'+Date.now()+'-'+crypto.getRandomValues(new Uint32Array(1))[0].toString(16);}
function timezone(){try{return Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Riga';}catch(_){return'Europe/Riga';}}
function transport(action,payload={}){
  return new Promise((resolve,reject)=>{if(!API)return reject(new Error('BACKEND_NOT_CONFIGURED'));if(!tg||!tg.initData)return reject(new Error('TELEGRAM_REQUIRED'));if(pendingResolver)return reject(new Error('REQUEST_IN_PROGRESS'));
    pendingResolver={action,resolve,reject};$('transport').action=API+'/api';$('txAction').value=action;$('txInit').value=tg.initData;$('txPayload').value=JSON.stringify(payload);$('transport').submit();requestTimer=setTimeout(()=>{if(pendingResolver){pendingResolver=null;reject(new Error('NETWORK_TIMEOUT'));}},15000);
  });
}
window.addEventListener('message',e=>{const d=e.data;if(!d||d.source!=='rform-tc-v1'||!pendingResolver)return;clearTimeout(requestTimer);const p=pendingResolver;pendingResolver=null;const res=d.payload||{};if(res.action&&res.action!==p.action&&res.ok!==false)return p.reject(new Error('RESPONSE_MISMATCH'));res.ok===false?p.reject(new Error(res.error||'REQUEST_FAILED')):p.resolve(res);});
function saveDraft(data){localStorage.setItem('rform_tc_v1_draft',JSON.stringify({saved_at:new Date().toISOString(),data}));}
function loadDraft(){try{return JSON.parse(localStorage.getItem('rform_tc_v1_draft')||'null');}catch(_){return null;}}
function setPending(obj){if(obj)localStorage.setItem('rform_tc_v1_pending',JSON.stringify(obj));else localStorage.removeItem('rform_tc_v1_pending');renderPending();}
function getPending(){try{return JSON.parse(localStorage.getItem('rform_tc_v1_pending')||'null');}catch(_){return null;}}
function renderPending(){$('pendingBox').classList.toggle('hidden',!getPending());}
function renderHome(){if(profile&&profile.active_checkpoint_text){$('activeCheckpointText').textContent=profile.active_checkpoint_text;$('activeCheckpoint').classList.remove('hidden');}else $('activeCheckpoint').classList.add('hidden');renderPending();show('home');}
function buildCheck(){return{session_date:today(),training_goal:value('trainingGoal'),exercise_name:value('exerciseName'),plan_load:n('planLoad'),actual_load:n('actualLoad'),load_unit:'кг',plan_sets:n('planSets'),actual_sets:n('actualSets'),plan_reps:n('planReps'),actual_reps:n('actualReps'),target_rir:value('targetRir'),actual_rir:value('actualRir'),effort:value('effort'),quality_rating:value('qualityRating'),pain_0_10:n('pain'),quality_comment:value('qualityComment'),overall_result:value('overallResult'),additional_event:value('additionalEvent')};}
function validateCheck(c){if(!c.exercise_name||!c.actual_sets||!c.actual_reps||!c.overall_result)return'Заполните ключевое упражнение, фактические подходы/повторы и итог.';if(!c.actual_rir&&!c.effort)return'Укажите RIR или ощущение сложности.';if(c.pain_0_10!==''&&(c.pain_0_10<0||c.pain_0_10>10))return'Боль указывается от 0 до 10.';return'';}
function renderResult(check){currentCheck=check;const a=check.analysis||{};$('resFact').textContent=a.fact||'—';$('resSignal').textContent=a.signal||'—';$('resInterpretation').textContent=a.interpretation||'—';$('resDecision').textContent=a.decision_direction||'—';$('resCheckpoint').textContent=a.checkpoint||'—';$('checkpointText').value=a.checkpoint||'';let c=a.comparison_note||'';if(a.trend_status==='OBSERVED_TENDENCY')c+=' Наблюдается повторяющаяся тенденция по трём сопоставимым Check.';$('comparison').textContent=c;$('checkpointActions').classList.remove('hidden');$('nextDateBox').classList.add('hidden');$('checkpointEdit').classList.add('hidden');$('explanation').classList.add('hidden');show('resultView');}
function renderHistory(){const box=$('historyList');box.innerHTML='';if(!history.length){box.innerHTML='<div class="panel">История пока пуста.</div>';return;}history.slice().reverse().forEach(h=>{const d=document.createElement('div');d.className='panel';const a=h.analysis||{};d.innerHTML='<div class="step"></div><div class="bigText"></div><p class="muted"></p>';d.children[0].textContent=h.session_date||'';d.children[1].textContent=a.signal||'Check сохранён';d.children[2].textContent=a.checkpoint||'';box.appendChild(d);});}
async function bootstrap(){show('loading');if(!tg||!tg.initData){show('telegramOnly');return;}tg.ready();tg.expand();try{tg.setHeaderColor&&tg.setHeaderColor('#0B1016');tg.setBackgroundColor&&tg.setBackgroundColor('#0B1016');}catch(_){}
  if(!API){banner('Staging backend ещё не подключён.');show('telegramOnly');return;}
  try{const r=await transport('bootstrap',{});profile=r.profile||null;history=r.history||[];if(r.new_user){show('privacyIntro');}else renderHome();}catch(e){banner('Не удалось открыть Training Check: '+e.message);show('telegramOnly');}
}
$('consent').addEventListener('change',()=>{if($('consent').checked)show('onboarding');});
$('saveOnboarding').onclick=async()=>{if(!$('consent').checked)return banner('Нужно согласие на сохранение данных.');const goal=value('goal'),experience_level=value('experience'),rir_mode=value('rirMode');if(!goal||!experience_level||!rir_mode)return banner('Ответьте на три вопроса.');try{const r=await transport('onboarding_save',{goal,experience_level,rir_mode,timezone:timezone(),reminders_enabled:false,consent_store_data:true,is_test_user:false});profile=r.profile;history=[];renderHome();}catch(e){banner(e.message);}};
$('startCheck').onclick=()=>{const d=loadDraft();if(d&&d.data){Object.entries(d.data).forEach(([k,v])=>{const el=$(k);if(el)el.value=v;});}show('checkView');};
$('submitCheck').onclick=async()=>{const c=buildCheck(),err=validateCheck(c);if(err)return banner(err);saveDraft({trainingGoal:c.training_goal,exerciseName:c.exercise_name,planLoad:c.plan_load,actualLoad:c.actual_load,planSets:c.plan_sets,actualSets:c.actual_sets,planReps:c.plan_reps,actualReps:c.actual_reps,targetRir:c.target_rir,actualRir:c.actual_rir,effort:c.effort,qualityRating:c.quality_rating,pain:c.pain_0_10,qualityComment:c.quality_comment,overallResult:c.overall_result,additionalEvent:c.additional_event});const pending={event_id:eventId(),check:c};setPending(pending);$('submitCheck').disabled=true;try{const r=await transport('check_submit',pending);setPending(null);localStorage.removeItem('rform_tc_v1_draft');currentCheck=r.check;history.push(r.check);renderResult(r.check);}catch(e){banner('Факт сохранён на устройстве. Повторите отправку: '+e.message);}finally{$('submitCheck').disabled=false;}};
$('retryPending').onclick=async()=>{const p=getPending();if(!p)return;try{const r=await transport('check_submit',p);setPending(null);currentCheck=r.check;history.push(r.check);renderResult(r.check);}catch(e){banner(e.message);}};
$('confirmCheckpoint').onclick=async()=>{if(!currentCheck)return;try{await transport('checkpoint_confirm',{check_id:currentCheck.check_id,checkpoint:currentCheck.analysis.checkpoint});profile.active_checkpoint_text=currentCheck.analysis.checkpoint;profile.active_checkpoint_check_id=currentCheck.check_id;$('checkpointActions').classList.add('hidden');$('nextDateBox').classList.remove('hidden');banner('Контрольная точка зафиксирована.');}catch(e){banner(e.message);}};
$('editCheckpoint').onclick=()=>{$('checkpointEdit').classList.remove('hidden');};
$('saveCheckpointEdit').onclick=async()=>{const cp=value('checkpointText');if(!cp)return banner('Введите контрольную точку.');try{await transport('checkpoint_change',{check_id:currentCheck.check_id,checkpoint:cp});currentCheck.analysis.checkpoint=cp;profile.active_checkpoint_text=cp;$('resCheckpoint').textContent=cp;$('checkpointEdit').classList.add('hidden');$('checkpointActions').classList.add('hidden');$('nextDateBox').classList.remove('hidden');banner('Изменение зафиксировано.');}catch(e){banner(e.message);}};
$('explainCheckpoint').onclick=()=>{const a=currentCheck&&currentCheck.analysis||{};$('explanation').textContent='Факт: '+(a.fact||'—')+' Сигнал: '+(a.signal||'—')+' Интерпретация — гипотеза, а не доказанный диагноз или тренд. Поэтому система предлагает проверить один вопрос, а не менять сразу несколько параметров.';$('explanation').classList.remove('hidden');};
$('saveNextDate').onclick=async()=>{const d=value('nextDate');if(!d)return banner('Выберите дату.');try{await transport('next_date_save',{check_id:currentCheck.check_id,next_date:d});profile.next_checkpoint_date=d;banner('Следующая дата сохранена.');renderHome();}catch(e){banner(e.message);}};
$('noNextDate').onclick=async()=>{try{await transport('next_date_save',{check_id:currentCheck.check_id,next_date:''});renderHome();}catch(e){banner(e.message);}};
$('showHistory').onclick=async()=>{try{const r=await transport('history',{});history=r.history||[];renderHistory();show('historyView');}catch(e){banner(e.message);}};
$('showSettings').onclick=()=>{$('remindersEnabled').checked=!!(profile&&profile.reminders_enabled);show('settingsView');};
$('saveSettings').onclick=async()=>{try{const r=await transport('settings_save',{reminders_enabled:$('remindersEnabled').checked,timezone:timezone()});profile=r.profile;banner('Настройки сохранены.');renderHome();}catch(e){banner(e.message);}};
$('showPrivacy').onclick=()=>show('privacyView');
$('deleteData').onclick=async()=>{if(!confirm('Удалить связь Training Check с вашим Telegram-профилем? Это действие нельзя отменить.'))return;try{await transport('delete_data',{});profile=null;history=[];localStorage.removeItem('rform_tc_v1_draft');setPending(null);banner('Данные удалены.');show('privacyIntro');$('consent').checked=false;}catch(e){banner(e.message);}};
$('portablePrompt').onclick=async()=>{try{const r=await transport('portable_prompt',{});$('promptText').value=r.prompt||'';show('promptView');}catch(e){banner(e.message);}};
$('copyPrompt').onclick=async()=>{try{await navigator.clipboard.writeText($('promptText').value);banner('Скопировано.');}catch(_){$('promptText').select();document.execCommand('copy');banner('Скопировано.');}};
$('sharePrompt').onclick=()=>{const text=$('promptText').value;if(!text)return;const url='https://t.me/share/url?url=&text='+encodeURIComponent(text.slice(0,3900));tg&&tg.openTelegramLink?tg.openTelegramLink(url):window.open(url,'_blank');};
document.querySelectorAll('[data-back],[data-home]').forEach(b=>b.onclick=renderHome);
bootstrap();
})();
