const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(__dirname+'/../owner_bot_v1.gs','utf8');
const echo='https://script.googleusercontent.com/macros/echo?secret-url-marker=1';
function setup(responses,brokenLog=false,code=source){const calls=[],logs=[];const ctx={PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'https://script.google.com/macros/s/fixture/exec'})},UrlFetchApp:{fetch:(url,opt)=>{calls.push({url,opt});const r=responses.shift();if(!r)throw Error('Unexpected replay');if(r.error)throw Error(r.error);return {getResponseCode:()=>r.status,getAllHeaders:()=>{if(r.headersError)throw Error('private-header-error');return r.headers||{}},getContentText:()=>r.raw??JSON.stringify(r.body)};}},console:{log:s=>{if(brokenLog)throw Error('logging unavailable');logs.push(s)}}};vm.createContext(ctx);vm.runInContext(code,ctx);return{calls,logs,run:(op='read')=>ctx.rformOwnerBotV1ApiPost_({operation:op,nonce:'private-nonce',signature:'private-signature'}),trace:()=>JSON.parse(logs[0])};}
let count=0;function test(n,f){f();count++;console.log('PASS '+n)}
test('404 logs both stages and omits response, URL and signed credentials',()=>{const s=setup([{status:302,headers:{Location:echo}},{status:404,raw:'private-response-marker'}]);let error;try{s.run()}catch(e){error=e};assert.match(error.message,/HTTP 404/);assert(!error.message.includes('private-response-marker'));const t=s.trace();assert.equal(t.postResponse.httpStatus,302);assert.equal(t.resultResponse.httpStatus,404);assert.equal(t.stage,'NON_JSON');assert.equal(t.json,false);assert.equal(t.postAttempts,1);assert.equal(t.getAttempts,1);assert.equal(s.calls.length,2);for(const secret of ['secret-url-marker','private-nonce','private-signature','private-response-marker'])assert(!s.logs.join('').includes(secret));});
test('successful READ emits exactly one OK summary without queue data',()=>{const s=setup([{status:302,headers:{Location:echo}},{status:200,body:{ok:true,queue:['private-queue-marker']}}]);assert(s.run().ok);assert.equal(s.logs.length,1);assert.equal(s.trace().outcome,'OK');assert.equal(s.trace().stage,'DONE');assert(!s.logs[0].includes('private-queue-marker'));assert.equal(s.calls[1].opt.payload,undefined);});
test('GET failure identifies GET and never replays POST',()=>{const s=setup([{status:302,headers:{Location:echo}},{error:'private-network-error'}]);assert.throws(()=>s.run(),/network/);assert.equal(s.trace().stage,'GET');assert.equal(s.trace().getAttempts,1);assert.equal(s.calls.length,2);assert(!s.logs[0].includes('private-network-error'));});
test('POST failure identifies POST and makes no retry',()=>{const s=setup([{error:'network'}]);assert.throws(()=>s.run());assert.equal(s.trace().stage,'POST');assert.equal(s.trace().getAttempts,0);assert.equal(s.calls.length,1);});
test('second sign-in redirect is classified but never followed',()=>{const s=setup([{status:302,headers:{Location:echo}},{status:302,headers:{Location:'https://accounts.google.com/ServiceLogin?private-sign-in-marker=1'},raw:''}]);assert.throws(()=>s.run());assert.equal(s.trace().resultResponse.redirectRoute,'GOOGLE_SIGN_IN');assert.equal(s.calls.length,2);assert(!s.logs[0].includes('private-sign-in-marker'));});
test('foreign first redirect is rejected and URL is not logged',()=>{const s=setup([{status:302,headers:{Location:'https://private-host-marker.invalid/path?secret=1'}}]);assert.throws(()=>s.run(),/unsupported/);assert.equal(s.trace().stage,'FIRST_REDIRECT_REJECTED');assert.equal(s.trace().postResponse.redirectRoute,'OTHER');assert.equal(s.calls.length,1);assert(!s.logs[0].includes('private-host-marker'));});
test('telemetry logging failure cannot turn successful read into failure',()=>{const s=setup([{status:200,body:{ok:true}}],true);assert(s.run().ok);assert.equal(s.calls.length,1);});
test('metadata inspection failure cannot change direct JSON success',()=>{const s=setup([{status:200,body:{ok:true},headersError:true}]);assert(s.run().ok);assert.equal(s.trace().postResponse.metadataUnavailable,true);});
test('content actions emit no READ telemetry and retain one POST plus one GET',()=>{const s=setup([{status:302,headers:{Location:echo}},{status:200,body:{ok:true}}]);assert(s.run('content_action').ok);assert.equal(s.logs.length,0);assert.equal(s.calls.length,2);});
test('baseline and candidate send identical requests for READ and actions',()=>{const baseline=fs.readFileSync(__dirname+'/fixtures/owner_bot_v1.0.4_baseline.gs','utf8');for(const op of ['read','content_action','queue_publication_approval']){const replies=[{status:302,headers:{Location:echo}},{status:200,body:{ok:true}}];const a=setup(structuredClone(replies),false,baseline),b=setup(structuredClone(replies));assert(a.run(op).ok);assert(b.run(op).ok);assert.equal(JSON.stringify(a.calls),JSON.stringify(b.calls));}});
console.log(count+' observability tests PASS; mocked network only');

