const STORE='life_planner_private_v1';
let db=null;
const $=(s,e=document)=>e.querySelector(s);const $$=(s,e=document)=>[...e.querySelectorAll(s)];
async function gunzipBytes(bytes){const ds=new DecompressionStream('gzip');const stream=new Blob([bytes]).stream().pipeThrough(ds);return new Uint8Array(await new Response(stream).arrayBuffer());}
function b64uBytes(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
function fmt(n,u=''){if(n===null||n===undefined||Number.isNaN(Number(n)))return '—';const v=Number(n);return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(v)+(u?' '+u:'');}
function pct(v){return Math.max(0,Math.min(100,Math.round(v||0)));}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function save(){localStorage.setItem(STORE,JSON.stringify(db));}
function initRuntime(plan){return {tasks:{},milestones:{},results:{},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};}
async function decryptSeed(keyText){const key=await crypto.subtle.importKey('raw',b64uBytes(keyText),{name:'AES-GCM'},false,['decrypt']);const compressed=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64uBytes(SEED.iv),additionalData:new TextEncoder().encode(SEED.aad)},key,b64uBytes(SEED.data));const plain=await gunzipBytes(new Uint8Array(compressed));return JSON.parse(new TextDecoder().decode(plain));}
function validatePlan(p){if(!p||p.type!=='LIFE_PLANNER_INIT'||p.version!==1||!Array.isArray(p.goals)||!p.period)throw new Error('Ожидается LIFE_PLANNER_INIT v1');return p;}
function goalProgress(g){if(g.type==='project'){const ms=g.milestones||[];if(!ms.length)return 0;const done=ms.filter(m=>db.runtime.milestones[g.key+'::'+m.key]).length;return 100*done/ms.length;}const m=(g.resultMetrics||[]).find(x=>x.primary)||(g.resultMetrics||[])[0];if(!m)return 0;const entries=db.runtime.results[g.key+'::'+m.key]||[];let val=entries.length?entries[entries.length-1].value:m.baseline;const b=Number(m.baseline),t=Number(m.target),x=Number(val);if(m.successRule==='target_value')return x===t?100:(b===t?0:100*(x-b)/(t-b));if(m.successRule==='lower_better')return b===t?(x<=t?100:0):100*(b-x)/(b-t);if(m.successRule==='range')return x>=m.rangeMin&&x<=m.rangeMax?100:0;return b===t?(x>=t?100:0):100*(x-b)/(t-b);}
function overall(){const gs=db.plan.goals||[];return gs.length?gs.reduce((a,g)=>a+goalProgress(g),0)/gs.length:0;}
function resultValue(g,m){const e=db.runtime.results[g.key+'::'+m.key]||[];return e.length?e[e.length-1].value:m.baseline;}
function periodPct(){const a=new Date(db.plan.period.start+'T00:00:00'),b=new Date(db.plan.period.end+'T23:59:59'),n=new Date();return pct(100*(n-a)/(b-a));}
function currentMonth(){return new Date().toISOString().slice(0,7)}
function navHtml(){return `<div class="nav"><button data-tab="today">Сегодня</button><button data-tab="goals">Цели</button><button data-tab="months">Месяцы</button><button data-tab="data">Данные</button></div>`}
function goalCard(g,compact=false){const pr=goalProgress(g);const metric=(g.resultMetrics||[]).find(x=>x.primary)||(g.resultMetrics||[])[0];let body='';if(g.type==='project'){const ms=(g.milestones||[]).map(m=>{const k=g.key+'::'+m.key;return `<label class="milestone"><input type="checkbox" data-ms="${esc(k)}" ${db.runtime.milestones[k]?'checked':''}><span>${esc(m.title)}</span></label>`}).join('');body=`<div class="metric-row"><div><div class="metric-value">${pct(pr)}%</div><div class="metric-sub">этапы проекта</div></div></div><div class="progress"><span style="width:${pct(pr)}%"></span></div>${compact?'':`<div class="milestones">${ms}</div>`}`;}else if(metric){const v=resultValue(g,metric);body=`<div class="metric-row"><div><div class="metric-value">${fmt(v,metric.unit)}</div><div class="metric-sub">цель: ${fmt(metric.target,metric.unit)}</div></div>${compact?'':`<button class="btn primary" data-result="${esc(g.key)}::${esc(metric.key)}">Обновить</button>`}</div><div class="progress"><span style="width:${pct(pr)}%"></span></div>`}
return `<div class="goal"><div class="goal-head"><div><div class="goal-title">${esc(g.name)}</div><div class="goal-meta"><span class="pill">P${g.priority}</span><span class="pill">до ${esc(g.deadline)}</span><span class="pill">${g.type==='project'?'проект':'результат'}</span></div></div><div class="nowrap small muted">${pct(pr)}%</div></div>${body}${compact?'':`<div class="small muted">${esc(g.note||'')}</div>`}</div>`}
function renderToday(){const p=db.plan,w=p.week||null;const tasks=w?(w.tasks||[]):[];const done=tasks.filter((_,i)=>db.runtime.tasks[(w.start||'week')+'::'+i]).length;const priority=[...(p.goals||[])].sort((a,b)=>b.priority-a.priority).slice(0,2);return `<div class="grid two"><div class="card"><h2>Текущий цикл</h2><div class="kpis"><div class="kpi"><div class="v">${pct(overall())}%</div><div class="l">общий прогресс</div></div><div class="kpi"><div class="v">${periodPct()}%</div><div class="l">период прошёл</div></div><div class="kpi"><div class="v">${done}/${tasks.length}</div><div class="l">задач недели</div></div></div><div style="height:14px"></div><div class="progress"><span style="width:${pct(overall())}%"></span></div></div><div class="card"><h2>Ограничение системы</h2><div class="muted" style="line-height:1.5">${esc(p.profile.workNote||'')}</div></div></div><div style="height:14px"></div><div class="grid two"><div class="card"><h2>Неделя</h2>${w?`<div class="muted" style="line-height:1.45;margin-bottom:14px"><b>Фокус:</b> ${esc(w.focus)}<br><b>Вызов:</b> ${esc(w.challenge)}</div><div class="tasks">${tasks.map((t,i)=>{const k=(w.start||'week')+'::'+i,d=!!db.runtime.tasks[k];return `<label class="task ${d?'done':''}"><input type="checkbox" data-task="${esc(k)}" ${d?'checked':''}><span><div class="task-title">${esc(t.title)}</div><div class="task-sub">${esc(t.easy||'')}</div></span></label>`}).join('')}</div>`:`<div class="empty muted">Для текущего периода недельный план не задан.</div>`}</div><div class="card"><h2>Ключевые цели</h2>${priority.map(g=>goalCard(g,true)).join('')}</div></div>`}
function renderGoals(){return `<div class="card"><h2>Цели периода</h2>${(db.plan.goals||[]).map(g=>goalCard(g,false)).join('')}</div>`}
function renderMonths(){const cm=currentMonth();return `<div class="card"><h2>Roadmap</h2>${(db.plan.months||[]).map(m=>`<details class="month" ${m.month===cm?'open':''}><summary><span class="month-title">${esc(m.month)} · ${esc(m.theme)}</span><span class="pill">${(m.steps||[]).length} шаг.</span></summary><div class="month-outcome">${esc(m.outcome||'')}</div>${(m.steps||[]).length?`<ul class="steps">${m.steps.map(s=>`<li><b>${esc(s.title)}</b> <span class="pill">${esc(s.importance)}</span></li>`).join('')}</ul>`:''}</details>`).join('')}</div>`}
function renderData(){return `<div class="grid two"><div class="card"><h2>Импорт плана</h2><p class="muted">Вставь новый LIFE_PLANNER_INIT v1. Текущий runtime-прогресс будет сброшен после подтверждения.</p><textarea id="importText" class="textarea" placeholder='{ "type": "LIFE_PLANNER_INIT", ... }'></textarea><div class="btns" style="margin-top:10px"><button id="importBtn" class="btn primary">Проверить и заменить</button></div></div><div class="card"><h2>Резервная копия</h2><p class="privacy">Данные и отметки сохраняются только в localStorage этого браузера. Исходный персональный план в GitHub не хранится открытым: стартовый пакет зашифрован, ключ был передан только во фрагменте стартовой ссылки.</p><div class="btns"><button id="exportBtn" class="btn">Экспортировать состояние</button><button id="resetBtn" class="btn danger">Удалить локальные данные</button></div><div style="height:16px"></div><div class="small muted">Период: ${esc(db.plan.period.start)} — ${esc(db.plan.period.end)}<br>Последнее локальное изменение: ${esc(db.runtime.updatedAt||'—')}</div></div></div>`}
function render(tab='today'){const p=db.plan;const root=$('#root');root.innerHTML=`<div class="app"><div class="top"><div class="brand"><h1>Life Planner</h1><p>${esc(p.profile.name||'')} · ${esc(p.period.start)} — ${esc(p.period.end)}</p></div><div class="badge">PRIVATE LOCAL STATE</div></div>${navHtml()}<section id="today" class="section"></section><section id="goals" class="section"></section><section id="months" class="section"></section><section id="data" class="section"></section></div>`;$('#today').innerHTML=renderToday();$('#goals').innerHTML=renderGoals();$('#months').innerHTML=renderMonths();$('#data').innerHTML=renderData();switchTab(tab);bind();}
function switchTab(tab){$$('.section').forEach(x=>x.classList.toggle('active',x.id===tab));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));}
function bind(){$$('.nav button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$$('[data-task]').forEach(i=>i.onchange=()=>{db.runtime.tasks[i.dataset.task]=i.checked;db.runtime.updatedAt=new Date().toISOString();save();render('today')});$$('[data-ms]').forEach(i=>i.onchange=()=>{db.runtime.milestones[i.dataset.ms]=i.checked;db.runtime.updatedAt=new Date().toISOString();save();render('goals')});$$('[data-result]').forEach(b=>b.onclick=()=>{const [gk,mk]=b.dataset.result.split('::');const g=db.plan.goals.find(x=>x.key===gk),m=g?.resultMetrics?.find(x=>x.key===mk);if(!m)return;const cur=resultValue(g,m);const raw=prompt(`${m.name}\nТекущее значение: ${cur}\nВведите новое значение (${m.unit}):`,String(cur));if(raw===null)return;const value=Number(String(raw).replace(/\s/g,'').replace(',','.'));if(Number.isNaN(value)){alert('Нужно числовое значение');return;}const k=gk+'::'+mk;(db.runtime.results[k]??=[]).push({date:new Date().toISOString().slice(0,10),value});db.runtime.updatedAt=new Date().toISOString();save();render('goals');toast('Показатель обновлён')});$('#importBtn').onclick=()=>{try{const p=validatePlan(JSON.parse($('#importText').value));if(!confirm('Заменить текущий план? Локальный прогресс будет сброшен.'))return;db={plan:p,runtime:initRuntime(p)};save();render('today');toast('Новый план загружен')}catch(e){alert('Ошибка: '+e.message)}};$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='life-planner-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('#resetBtn').onclick=()=>{if(confirm('Удалить локальный план и все отметки из этого браузера?')){localStorage.removeItem(STORE);location.reload()}}}
function unlockScreen(msg=''){document.getElementById('root').innerHTML=`<div class="app"><div class="unlock card"><h1>Life Planner</h1><p class="muted">Для первого запуска открой приватную стартовую ссылку, полученную при развёртывании, либо импортируй LIFE_PLANNER_INIT v1.</p>${msg?`<p class="error">${esc(msg)}</p>`:''}<textarea id="firstImport" class="textarea" placeholder='{ "type": "LIFE_PLANNER_INIT", ... }'></textarea><div class="btns" style="margin-top:10px"><button id="firstImportBtn" class="btn primary">Импортировать</button></div></div></div>`;$('#firstImportBtn').onclick=()=>{try{const p=validatePlan(JSON.parse($('#firstImport').value));db={plan:p,runtime:initRuntime(p)};save();render()}catch(e){unlockScreen('Ошибка: '+e.message)}}}
async function boot(){try{const saved=localStorage.getItem(STORE);if(saved){db=JSON.parse(saved);validatePlan(db.plan);render();return;}const h=location.hash.match(/^#k=([A-Za-z0-9_-]+)$/);if(h){const p=validatePlan(await decryptSeed(h[1]));db={plan:p,runtime:initRuntime(p)};save();history.replaceState(null,'',location.pathname+location.search);render();toast('Приватный план загружен');return;}unlockScreen();}catch(e){unlockScreen('Не удалось открыть стартовый пакет: '+e.message)}}
boot();
